version: "3.5"
services:
  laravel-react_server-app:
    build: ./docker/laravel
    container_name: laravel-react_server-app
    depends_on:
      - laravel-react_db
      - laravel-react_redis
    volumes:
      - ./:/application

  laravel-react_db:
    image: mysql:5.7
    container_name: laravel-react_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel-react_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user-creds
    ports:
      - "8083:3306"

  laravel-react_nginx:
    image: nginx
    container_name: laravel-react_nginx
    ports:
      - "8082:8000"
    volumes:
      - ./:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-react_server-app

  laravel-react_redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  laravel-react_node:
    build: .
    container_name: laravel-react_node
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
    - NODE_ENV=development
    - CHOKIDAR_USEPOLLING=true