version: "3.5"
services:
  laravel-react_redis:
    container_name: laravel-react_redis
    image: redis
    ports:
      - "6379:6379"

  laravel-react_db:
    image: mysql:5.7
    container_name: laravel-react_db
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel_react_db
      - MYSQL_USER=laravel-user
      - MYSQL_PASSWORD=laravel-user-pass
    ports:
      - "8083:3306"

  laravel-react_server-app:
    build:
      context: .
      dockerfile: laravel.dockerfile
    container_name: laravel-react_server-app
    depends_on:
      - laravel-react_db
      - laravel-react_redis
    volumes:
      - ./:/application

  laravel-react_nginx:
    image: nginx
    container_name: laravel-react_nginx
    depends_on:
      - laravel-react_server-app
    ports:
      - "8082:8082"
    volumes:
      - ./:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  laravel-react_node:
    build:
      context: .
      dockerfile: react.dockerfile
    container_name: laravel-react_node
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command:
      sh -c "npm run watch"